"""Stable public configuration API for the coupled runtime.

The implementation is split by responsibility while this module preserves all
legacy ``from src.config import ...`` imports.
"""

from .cli_adapter import (
    _nonnegative_float,
    _positive_float,
    build_ion_template_from_args,
)
from .constants import (
    ATOMIC_MASS_CONSTANT,
    DEFAULT_STATIC_FIELD_PATH,
    DT_LIMITER_NAMES,
    N2_MOLAR_MASS_KG_PER_MOL,
    N2_MOLECULAR_MASS_KG,
    PARTICLE_ACTIVE,
    PARTICLE_CAPILLARY_BUFFER,
    PARTICLE_DOMAIN_OUT,
    PARTICLE_ELECTRODE_HIT,
    PARTICLE_FRAGMENTED,
    PARTICLE_RADIAL_OUT,
    PARTICLE_STATUS_NAMES,
    PARTICLE_Z_EXIT,
    PROJECT_ROOT,
    SLOT_ACTIVE,
    SLOT_CAPILLARY,
    SLOT_FREE,
    UNIVERSAL_GAS_CONSTANT_J_PER_MOL_K,
)
from .contracts import (
    CollisionBatchUpdate,
    CollisionOutcome,
    LocalStateBatch,
    ProgressCallback,
    SimulationProgress,
    SimulationResult,
)
from .factories import (
    make_execution_config,
    make_ion_template,
    make_output_config,
    make_simulation_config,
)
from .json_config import (
    CONFIG_SCHEMA_VERSION,
    ConfigDocument,
    config_document_from_dict,
    config_document_to_dict,
    dump_config_document,
    dump_config_json,
    load_config_document,
    load_config_json,
    make_config_document,
)
from .models import (
    ExecutionConfig,
    IonTemplate,
    OutputConfig,
    SimulationConfig,
)
from .validation import (
    normalize_execution_config,
    normalize_ion_template,
    normalize_output_config,
    normalize_simulation_config,
    validate_execution_config,
    validate_ion_template,
    validate_output_config,
    validate_simulation_config,
)

__all__ = [
    "ATOMIC_MASS_CONSTANT",
    "CONFIG_SCHEMA_VERSION",
    "CollisionBatchUpdate",
    "CollisionOutcome",
    "ConfigDocument",
    "DEFAULT_STATIC_FIELD_PATH",
    "DT_LIMITER_NAMES",
    "ExecutionConfig",
    "IonTemplate",
    "LocalStateBatch",
    "N2_MOLAR_MASS_KG_PER_MOL",
    "N2_MOLECULAR_MASS_KG",
    "OutputConfig",
    "PARTICLE_ACTIVE",
    "PARTICLE_CAPILLARY_BUFFER",
    "PARTICLE_DOMAIN_OUT",
    "PARTICLE_ELECTRODE_HIT",
    "PARTICLE_FRAGMENTED",
    "PARTICLE_RADIAL_OUT",
    "PARTICLE_STATUS_NAMES",
    "PARTICLE_Z_EXIT",
    "PROJECT_ROOT",
    "ProgressCallback",
    "SLOT_ACTIVE",
    "SLOT_CAPILLARY",
    "SLOT_FREE",
    "SimulationConfig",
    "SimulationProgress",
    "SimulationResult",
    "UNIVERSAL_GAS_CONSTANT_J_PER_MOL_K",
    "build_ion_template_from_args",
    "config_document_from_dict",
    "config_document_to_dict",
    "dump_config_document",
    "dump_config_json",
    "load_config_document",
    "load_config_json",
    "make_config_document",
    "make_execution_config",
    "make_ion_template",
    "make_output_config",
    "make_simulation_config",
    "normalize_execution_config",
    "normalize_ion_template",
    "normalize_output_config",
    "normalize_simulation_config",
    "validate_execution_config",
    "validate_ion_template",
    "validate_output_config",
    "validate_simulation_config",
]
